/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.com.hyunseda.market.presentation;

import co.com.hyunseda.market.domain.Product;
import co.com.hyunseda.market.domain.acess.Factory;
import co.com.hyunseda.market.domain.acess.IOrderRepository;
import co.com.hyunseda.market.domain.acess.IPayRepository;
import co.com.hyunseda.market.domain.acess.IProductRepository;
import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.OrderService;
import co.com.hyunseda.market.service.PayService;
import co.com.hyunseda.market.service.ProductService;
import co.com.hyunseda.market.service.ShoppingCartService;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Laura Sofia
 */
public class GUIREGISTRARUSUARIO extends javax.swing.JFrame {
  

    private CategoryService categoryService;
    private ProductService productService;
    private ShoppingCartService shoppingCartService;
    private PayService payService;
    private OrderService orderService;

    double totalPago;
    long codigoCuenta;
    String plataformaPago;
    long orderId;
    long payId;
    /**
     * Creates new form GUIREGISTRARUSUARIO
     */
    public GUIREGISTRARUSUARIO() {
        initComponents();
    } 
    
    public GUIREGISTRARUSUARIO(double totalPago) {
        initComponents();
        this.totalPago = totalPago;
        this.codigoCuenta = codigoCuenta;
        this.plataformaPago = plataformaPago;
        
         txtValorPago.setText(String.valueOf(totalPago));
         setLocationRelativeTo(null);
        setSize(450, 350);
    }
    public GUIREGISTRARUSUARIO(double totalPago,CategoryService categoryService, ProductService productService, ShoppingCartService shoppingCartService) {
        initComponents();
        
              
        IProductRepository repo = Factory.getInstance().getProductRepository("default");
        new ProductService(repo);
           txtValorPago.setText(String.valueOf(totalPago));
        this.payId =payId;
        this.orderId = orderId;
        this.totalPago = totalPago;
        this.codigoCuenta = codigoCuenta;
        this.plataformaPago = plataformaPago;
        
        IPayRepository repoPay = Factory.getInstance().getPayRepository("default");
        this.payService = new PayService(repoPay);

        IOrderRepository repoOrder = Factory.getInstance().getOrderRepository("default");
        this.orderService = new OrderService(repoOrder);

        this.categoryService = categoryService;
        this.productService = productService;
        this.shoppingCartService = shoppingCartService;
       
        setLocationRelativeTo(null);
        setSize(450, 350);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        txtPago = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/curriculum(1).png"))); // NOI18N
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel3.setText("Factura");
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver);

        txtPago.setText("Registrar");
        txtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoActionPerformed(evt);
            }
        });
        jPanel2.add(txtPago);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(5, 2));

        jblNombre.setText("Nombre:");
        jPanel3.add(jblNombre);
        jPanel3.add(txtNombre);

        jblApellido.setText("Apellido:");
        jPanel3.add(jblApellido);
        jPanel3.add(txtApellido);

        jLabel7.setText("Email:");
        jPanel3.add(jLabel7);
        jPanel3.add(txtEmail);

        jblDireccion.setText("Dirección:");
        jblDireccion.setToolTipText("");
        jPanel3.add(jblDireccion);
        jPanel3.add(txtDireccion);

        jLabel4.setText("Valor del pago:");
        jPanel3.add(jLabel4);
        jPanel3.add(txtValorPago);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoActionPerformed
        
    txtValorPago.setText(String.valueOf(totalPago));
    String nombre = txtNombre.getText().trim();
    String apellido =txtApellido.getText().trim();
    String email= txtEmail.getText().trim();
    String direccion = txtDireccion.getText().trim(); 
    
    if(!nombre.isBlank()|| !apellido.isBlank()||!email.isBlank()||!direccion.isBlank())
    {
          Messages.showMessageDialog("Producto en camino", "Informacion");
    }else{
        Messages.showMessageDialog("Por favor ingresar la informacion solicitada", "Atención");
    }
    }//GEN-LAST:event_txtPagoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
         GUIPREVIEW abrir = new GUIPREVIEW(categoryService,productService,shoppingCartService);
        abrir.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIREGISTRARUSUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIREGISTRARUSUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIREGISTRARUSUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIREGISTRARUSUARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIREGISTRARUSUARIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jblApellido;
    private javax.swing.JLabel jblDireccion;
    private javax.swing.JLabel jblNombre;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JButton txtPago;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables
}
